### PR TITLE
PHP 7.1 in travis

### PR DESCRIPTION
**Pull request by kokspflanze**
added PHP 7.1 in travis for tests

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@kokspflanze i would not use the coverage report yet from 7.1 since its not stable already.

But building with it is fine - can you change back the coverage result to 7.0? After GA we can change that

**Comment by kokspflanze** [comment]
changed=)

**Comment by ThaDafinser** [comment]
Thanks!

**Comment by ThaDafinser** [comment]
I think it's time to create a stable tag of `1.3` (develop)

Using it now for some time

**Comment by kokspflanze** [comment]
@ThaDafinser yeah would be good, but we should merge develop in master.

**Comment by ThaDafinser** [comment]
yep, i will get into that

**Pull request merged**
