### PR TITLE
::class changes in `ZfcDatagrid\Renderer\JqGrid\View\Helper`

### PR DESCRIPTION
**Pull request by kokspflanze**

### CODE REVIEW

**Comment by kokspflanze** [comment]
@ThaDafinser maybe also smth for develop?

**Comment by ThaDafinser** [comment]
@kokspflanze sure - let's do a rebase and we merge both PRs and finally a pre-release

**Comment by kokspflanze** [comment]
conflict done

the build error, is already fix in https://github.com/ThaDafinser/ZfcDatagrid/pull/272

**Comment by kokspflanze** [comment]
https://github.com/zfc-datagrid/zfc-datagrid/pull/41

**Pull request closed without merging**
