### PR TITLE
 move to new repo

### PR DESCRIPTION
**Pull request by kokspflanze**
- [x] added new repo to packagist
- [x] added replace, in composer https://github.com/zfc-datagrid/zfc-datagrid/pull/1
- [x] added travis build (@ThaDafinser)
- [ ] set current repo to outdated on packagist (@ThaDafinser)
- [x] added rights on new repo
- [x]  update image paths https://github.com/zfc-datagrid/zfc-datagrid/pull/2

### CODE REVIEW

**Comment by kokspflanze** [comment]
@ZeinEddin added to the new repo as admin, should be okay from the rights, i hope=)

**Comment by ThaDafinser** [comment]
@kokspflanze travis is running: https://github.com/zfc-datagrid/zfc-datagrid/pull/39

Both of you should have enough rights now to add services as well on your own.

Deprecating the current package will be done, as soon as the new repo is complete ready (new services, changed readme, ...)

**Comment by kokspflanze** [comment]
@ThaDafinser everything should done now

i also readded coveralls.io in build matrix

**Comment by ThaDafinser** [comment]
Done :+1: 

https://packagist.org/packages/thadafinser/zfc-datagrid

**Comment by ThaDafinser** [comment]
Thank you for the fast move @kokspflanze

**Pull request closed without merging**
