### PR TITLE
renamed Type\String in Type\PhpString for PHP7 Support

### PR DESCRIPTION
**Pull request by kokspflanze**
Hi,

for the PHP7 Support i renamed the name of the `ZfcDatagrid\Column\Type\String` class in  `ZfcDatagrid\Column\Type\PhpString`.

### CODE REVIEW

**Comment by kokspflanze** [comment]
i think we can ignore https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/59463612, looks more like a little travis temp problem

**Comment by ThaDafinser** [comment]
I'm afraid that many people rely currently on `dev-master` and it will break with this update...

The PR is fine.

**Comment by kokspflanze** [comment]
We can add the old String class, and set it on deprecated, to remove it in next versions, what you think about that?

**Comment by ThaDafinser** [comment]
@kokspflanze yeah that would be good.

Also extend with Your `PhpString` the `String` class (so instanceof still works)

After that i merge it

**Comment by ThaDafinser** [comment]
Thank you

**Pull request merged**
