### PR TITLE
PDF options for row height paddings

### PR DESCRIPTION
**Pull request by blacktemplar**
Adds two new options for customizing the row height calculation in PDF renderer.

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@blacktemplar looks good to me.
Can you fix the remaining cs error? Then i can merge it
https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/165813652#L445

**Comment by ThaDafinser** [comment]
ping @blacktemplar

**Comment by blacktemplar** [comment]
Sorry for the late respond. I am quite new to this automatic checker tool, but the cs error was in a file, which I didn't change... I fixed it now.

**Comment by ThaDafinser** [comment]
Great! Thanks a lot @blacktemplar

**Pull request merged**
