### PR TITLE
merge master in develop

### PR DESCRIPTION
**Pull request by kokspflanze**
merge master in develop, nothing special=)

### CODE REVIEW

**Comment by ThaDafinser** [comment]
Thanks.

I added 2 new tags
old ZF2 only https://github.com/ThaDafinser/ZfcDatagrid/releases/tag/v1.2.1
ZF2 + ZF3 https://github.com/ThaDafinser/ZfcDatagrid/releases/tag/v1.3.0

**Comment by ThaDafinser** [comment]
I just reverted the v1.3.0 tag - needs to be a 2.0...because of the BC :smile:

**Comment by kokspflanze** [comment]
@ThaDafinser is there a BC break, did i missed smth?

**Comment by ThaDafinser** [comment]
@kokspflanze not my day sry :-1:  ..need to get some sleep :smile: 

the service change i was thinking of, was already in the `1.2.x` series and the PHP change + package deps are handled with composer anyway

**Comment by kokspflanze** [comment]
@ThaDafinser no problem, but what you think about, create a issue with the todos for version 2.0?

**Comment by ThaDafinser** [comment]
Yep.

Let's start here https://github.com/ThaDafinser/ZfcDatagrid/issues/249

**Pull request merged**
