### PR TITLE
Feature/mvc

### PR DESCRIPTION
**Pull request by ThaDafinser**

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@kokspflanze i added another PR with your commits, to test it with lowest/highest deps.

My question is why you need to require `2.7` at least. Was there a missing test until yet, that here the tests are still green?
https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/115256679#L299

**Comment by kokspflanze** [comment]
hi the problem is the config https://github.com/ThaDafinser/ZfcDatagrid/blob/feature/mvc/config/module.config.php#L213 in the migration guide @ https://zendframework.github.io/zend-servicemanager/migration/#invokables you can read to remove the invokables and work with the `Zend\ServiceManager\Factory\InvokableFactory` this change is in the zend-mvc 2.7 version, maybe we have also to update the zend-servicemanager to min 2.7

**Comment by ThaDafinser** [comment]
@kokspflanze AFAIU that migration guide is for the `3.x` and not for the `2.x` series.

`zend-mvc 2.7` would required `zend-servicemanager 2.7`
https://github.com/zendframework/zend-mvc/blob/release-2.7.3/composer.json#L18

When i'm not wrong, the current behaviour (before this PR) should work for the whole 2.x` series.

So this PR should target better `ZfcDatagrid 2.0` and there we could completely drop ZF2 and require ZF3

Or what do you think?

**Comment by ThaDafinser** [comment]
@kokspflanze i see now the problem you mean...
https://github.com/zendframework/zend-mvc/releases/tag/release-2.7.0

**Comment by kokspflanze** [comment]
yes the change come with the zend-mvc 2.7 release, so everyone who use zend-mvc 2.7 get the latest version of the ZfcDatagrid (with the fixes and less deprecated warnings), everybody else who set a lower version than 2.7 get https://github.com/ThaDafinser/ZfcDatagrid/releases/tag/v1.1.0 which has also no deprecated warnings.

The migration guide for 3.x include also 2.x changes, which can be used in 2.7+.

A other solution would be i revert the `Zend\ServiceManager\Factory\InvokableFactory` changes and use the older 'invokable'' system in the config and open a other PR for version 2.0, which will support 3.x of the Zend Framework.

**Comment by kokspflanze** [comment]
At the weekend i think about the dependency problem, i think its possible to fix it, if we remove `Zend\ServiceManager\Factory\InvokableFactory` and add a `Closure`.

**Comment by ThaDafinser** [comment]
continue in #230

**Pull request closed without merging**
