### PR TITLE
update for zend-mvc 2.7

### PR DESCRIPTION
**Pull request by kokspflanze**
- updated composer.json for min zend-mvc 2.7
- also added the zend-json for data-ranges
- removed Zend\ServiceManager\ServiceLocatorAwareInterface parts from Datagrid-Service and ViewHelpers, for the `Column\Formatter\GenerateLink` i added a old fallback for version 1.x
- changed some unit tests =(

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@kokspflanze i will get into this PR after #231 
That PR will make sure that it still works with the lowest dependencies defined (not only the latest)

**Comment by kokspflanze** [comment]
no problem, btw these changes require zend-mvc 2.7+ and sure i changed it in the composer.json

**Comment by jonathangreco** [comment]
Hi, when this features will be released please ?

**Comment by kokspflanze** [comment]
@ThaDafinser we have some open todos, at this fix?

**Comment by ThaDafinser** [comment]
@kokspflanze i'm currently testing it locally with some projects and the `2.5` mvc version

There is a BC in this PR anyway: You moved from invokables to alias and in my case this resulted in an error.

**Comment by kokspflanze** [comment]
yes if you overwrite the current services without a alias, than it result in a BC.

But with the Dependency Injection its already a BC in the config.

Or did you see other BC parts?

**Comment by ThaDafinser** [comment]
BC breaks until yet found
- `alias` instead of `invokable`
- ***ERR*** config cache won't work anymore, since you directly added there the factories
  - need to be moved to `Module.php` that it continue to work
- `setRendererService()` breaks custom services (like mine)
- no serviceLocator anymore
  - got some grids which depends on it (can  be a BC break)

So the change has more impact than thought until yet.

Open questions in my mind, how we could handle this
- required 2.7? (so people need to update mvc as well and need to correct anyway)
- should we do a new major?

Or should we check, if for the 2.x series we can somehow stay in the current way, without that BC.
And create a develop branch for the 3.x series?

For myself i need to read more here https://zendframework.github.io/zend-mvc/migration/
Still use personal the 2.5 mvc

**Comment by ThaDafinser** [comment]
@kokspflanze i just got it running.

I moved the service + viewHelper thing from `module.config.php` to `Module.php`

```php
namespace ZfcDatagrid;

class Module
{

    // ...

    public function getServiceConfig()
    {
// ...
    }

    public function getViewHelperConfig()
    {
// ...
    }
}
```

**Comment by ThaDafinser** [comment]
@kokspflanze @jonathangreco i merged it for now in the `develop` branch.

@kokspflanze did a good job keeping the BC compability
- cache still work
- serviceManager is still in

The changes look good, but i would like to wait a bit and gather more feedback.

Since this is in many cases a core component, a (yet undetected) BC break could break a lot of code

https://packagist.org/packages/thadafinser/zfc-datagrid#dev-master

@kokspflanze dunno how the git rebase / merge magic works to directly merge the PR into another branch, but your contribution is still in the commits
https://github.com/ThaDafinser/ZfcDatagrid/commits/develop

**Pull request closed without merging**
